---
title: Link Collection Resources4Research
author: Anna Lohmann
output: 
  html_document:
    theme: united
    toc: true
    toc_float: true

---
# Ressources Overview


## Guidelines/ Best practice  

r style guide  
https://style.tidyverse.org/  

The turing way  
https://the-turing-way.netlify.app/introduction/introduction  

FAIR  
https://fair-software.nl/  

## Data visualization
Color palettes (general)  
https://www.color-hex.com/color-palettes/?page=2

point shapes  
http://www.sthda.com/english/wiki/r-plot-pch-symbols-the-different-point-shapes-available-in-r

### ggplot

ggplot2: Elegant Graphics for Data Analysis - Hadley Wickham  
https://ggplot2-book.org/  


https://www.datacamp.com/community/tutorials/15-questions-about-r-plots  

https://r4ds.had.co.nz/data-visualisation.html  


## Data wrangling

join()  
https://dplyr.tidyverse.org/reference/join.html

expand()  \
https://tidyr.tidyverse.org/reference/expand.html

pivot_longer() [new version of gather()]  
https://tidyr.tidyverse.org/reference/pivot_longer.html

## R Markdown

web icons 
https://www.r-bloggers.com/icon-web-icons-for-rmarkdown/  

boxes  
https://stackoverflow.com/questions/47806200/create-a-comment-box-using-rmarkdown-html-file  

### Bookdown
https://bookdown.org/yihui/bookdown/


## Reproducibility

### R packages
Ebook Hadley Whickham  
https://r-pkgs.org/

https://purrr.tidyverse.org/reference/faq-adverbs-export.html  

Writing R extensions CRAN  
https://cran.r-project.org/doc/manuals/R-exts.pdf

### Research Compendium
https://github.com/benmarwick/rrtools  
https://github.com/annakrystalli/rrtools-repro-research  


### Docker

Rocker  
https://github.com/rocker-org/rocker

### Binder 
https://mybinder.readthedocs.io/en/latest/config_files.html    

### Continuos Integration  
https://docs.travis-ci.com/user/for-beginners  


### papaja
https://crsh.github.io/papaja_man/introduction.html  



## Simulation studies

### Random number generation




## Programming

Ebook Hadley Whickham - Advanced R  
http://adv-r.had.co.nz/

Ebook Efficiant R Programming ? - Colin Gillesspie, Robin Lovelace  
https://bookdown.org/csgillespie/efficientR/  
 


### Environments and namespaces  
http://blog.obeautifulcode.com/R/How-R-Searches-And-Finds-Stuff/  

### Tidy evaluation
https://mastering-shiny.org/action-tidy.html  

### Programming with ggplot and dplyr

Best practices for programming with ggplot2  
https://fishandwhistle.net/slides/rstudioconf2020/  
 

https://speakerdeck.com/hadley/tidy-evaluation-programming-with-ggplot2-and-dplyr  

https://stackoverflow.com/questions/45824409/how-to-combine-ggplot-and-dplyr-into-a-function  

https://ggplot2-book.org/programming.html  

https://stackoverflow.com/questions/26531615/difference-between-quote-and-expression-in-r

### Non standard evaluation
https://cran.r-project.org/web/packages/dplyr/vignettes/programming.html

### quasiquotation
https://rlang.r-lib.org/reference/quasiquotation.html  

### group_by() and ggplot
https://gist.github.com/ctufts/eaca046a72af650a9b12f9751d95ff8d



### Debugging

R Studio Webinar - Garrett Grolemund  
https://rstudio.com/resources/webinars/programming-part-2-debugging-code-in-rstudio/

RStudio Webinar - Amanda Gadrow  
https://rstudio.com/resources/webinars/debugging-techniques-in-rstudio/

### purrr

lesser known purrr tricks  
https://www.brodrigues.co/blog/2017-03-24-lesser_known_purrr/   


### Stuff that keeps coming up
Subsetting   
www2.stat.duke.edu/~cr173/Sta523_Fa15/slides/2015-09-14-subsetting.html  

Reordering Factors    
https://github.com/STAT545-UBC/Discussion/issues/52    


## Git 

Badges for readme  
https://gist.github.com/tterb/982ae14a9307b80117dbf49f624ce0e8  

Atlassian tutorials  
https://www.atlassian.com/git/tutorials  

Trouble shooting  
https://stackoverflow.com/questions/58030695/r-sweave-put-the-whole-code-of-the-rnw-file-in-appendix  

Git section from R package book  
https://r-pkgs.org/git.html  

## LaTex

dummy image generator  
https://dummyimage.com/

### knittr

### Sweave
https://cran.r-project.org/web/packages/stationery/vignettes/code_chunks.pdf  
https://beckmw.files.wordpress.com/2014/02/sweave_intro1.pdf  
https://stackoverflow.com/questions/58030695/r-sweave-put-the-whole-code-of-the-rnw-file-in-appendix  


## Python

### Style guide
https://www.python.org/dev/peps/pep-0008/  

## Collections of useful ressources
https://paulvanderlaken.com/2018/05/21/r-tips-and-tricks/  
http://wiki.mgto.org/doku.php/how_to_guides  
